<?php
namespace App\Http\Controllers\Api\Resident;
use App\Contracts\ResidentKnowledgeService;use App\Http\Controllers\Controller;use App\Http\Requests\Resident\ChangePasswordRequest;use App\Http\Requests\Resident\StoreReportRequest;use App\Http\Requests\Resident\UpdateProfileRequest;use App\Models\Advisory;use App\Models\EmergencyHotline;use App\Models\Purok;use App\Models\Report;use App\Models\ReportCategory;use App\Models\ReportStatusHistory;use App\Models\User;use App\Notifications\ReportActivityNotification;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;
class ResidentApiController extends Controller {
 private function ok(mixed $data,string $message='Request completed successfully.',array $meta=[]){return response()->json(['success'=>true,'message'=>$message,'data'=>$data]+($meta?['meta'=>$meta]:[]));}
 public function dashboard(Request $r){$q=Report::where('resident_id',$r->user()->id);$counts=(clone$q)->selectRaw('status,COUNT(*) total')->groupBy('status')->pluck('total','status');return $this->ok(['counts'=>['total'=>(clone$q)->count(),'pending'=>(int)($counts['pending']??0),'in_progress'=>(int)($counts['in_progress']??0),'resolved'=>(int)($counts['resolved']??0)],'recent_reports'=>(clone$q)->with(['category','purok'])->latest()->limit(5)->get()],'Dashboard retrieved successfully.');}
 public function reports(Request $r){$p=Report::where('resident_id',$r->user()->id)->with(['category','purok'])->latest()->paginate(15);return $this->ok($p->items(),'Reports retrieved successfully.',['current_page'=>$p->currentPage(),'last_page'=>$p->lastPage(),'per_page'=>$p->perPage(),'total'=>$p->total()]);}
 public function store(StoreReportRequest $r){$report=DB::transaction(function()use($r){$next=(int)Report::withTrashed()->lockForUpdate()->max('id')+1;$report=Report::create([...$r->safe()->except(['photos','confirm_accuracy']),'reference_number'=>'BF-'.now()->year.'-'.str_pad((string)$next,6,'0',STR_PAD_LEFT),'resident_id'=>$r->user()->id,'priority'=>'normal','status'=>'pending','validation_status'=>'unverified']);foreach($r->file('photos',[]) as $photo){$path=$photo->store("reports/{$report->id}",'public');$report->photos()->create(['path'=>$path,'original_name'=>$photo->getClientOriginalName(),'mime_type'=>$photo->getMimeType(),'size'=>$photo->getSize()]);}ReportStatusHistory::create(['report_id'=>$report->id,'changed_by'=>$r->user()->id,'to_status'=>'pending','notes'=>'Report submitted and awaiting validation.','created_at'=>now()]);$r->user()->notify(new ReportActivityNotification($report,'Report submitted',"Your report {$report->reference_number} is awaiting barangay validation."));User::where('role','admin')->where('status','active')->each(fn($a)=>$a->notify(new ReportActivityNotification($report,'New community report',"{$report->reference_number} was submitted.")));return $report->load(['category','purok','photos']);});return $this->ok($report,'Your report has been submitted successfully and is awaiting barangay validation.');}
 public function show(Request $r,Report $report){$this->authorize('view',$report);$report->load(['category','purok','photos','statusHistories','notes'=>fn($q)=>$q->where('is_resident_visible',true)]);unset($report->assignedStaff,$report->assignments);return $this->ok($report,'Report retrieved successfully.');}
 public function categories(){return $this->ok(ReportCategory::where('is_active',true)->orderBy('name')->get(),'Categories retrieved successfully.');} public function puroks(){return $this->ok(Purok::where('is_active',true)->orderBy('sort_order')->get(),'Puroks retrieved successfully.');}
 public function updates(){return $this->ok(Advisory::visibleToResidents()->latest('published_at')->paginate(15),'Updates retrieved successfully.');} public function update(Advisory $update){abort_unless(Advisory::visibleToResidents()->whereKey($update)->exists(),404);return $this->ok($update,'Update retrieved successfully.');}
 public function emergency(){return $this->ok(EmergencyHotline::where('is_active',true)->orderBy('sort_order')->get(),'Emergency information retrieved successfully.');}
 public function notifications(Request $r){return $this->ok($r->user()->notifications()->latest()->paginate(15),'Notifications retrieved successfully.');} public function notificationRead(Request $r,string $id){$n=$r->user()->notifications()->findOrFail($id);$n->markAsRead();return $this->ok($n,'Notification marked as read.');} public function notificationsReadAll(Request $r){$r->user()->unreadNotifications()->update(['read_at'=>now()]);return $this->ok(null,'All notifications marked as read.');}
 public function profile(Request $r){return $this->ok($r->user()->load('purok'),'Profile retrieved successfully.');} public function profileUpdate(UpdateProfileRequest $r){$r->user()->update($r->validated());return $this->ok($r->user()->fresh('purok'),'Profile updated successfully.');} public function password(ChangePasswordRequest $r){$r->user()->update(['password'=>Hash::make($r->password)]);return $this->ok(null,'Password changed successfully.');}
 public function assistant(Request $r,ResidentKnowledgeService $knowledge){$data=$r->validate(['question'=>['required','string','min:3','max:1000']]);$result=$knowledge->answer($data['question']);return response()->json(['success'=>$result['available'],'message'=>$result['answer'],'data'=>['sources'=>$result['sources']]],$result['available']?200:503);}
}
